server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.105.161:3306/testsell?useSSL=false
    username: zhuqiang
    password: zhuqiang@1234
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
  mvc:
    view:
      prefix: /
      suffix: .html
  thymeleaf:
    cache: false
url:
  homePageName: indexpage
  homePageLocation: http://localhost:8088/index
  loginViewName: loginpage
  loginPageLocation: http://localhost:8088/login
